### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by batchku** [arturoc/ofxAxisGrabber#2]
hello arturo,
i'm trying to compile ofxAxisGrabber's example and i get this error below;
i downloaded a zip from github and put it here:

/Users/ali/Dropbox/Soft Dev/openFrameworks 0.8.3/addons/ofxAxisGrabber-master/example

i'm running "make" from inside the example folder;
it seems that it's not finding the main ofx headerfiles;
any ideas?

---

jizbookpro:example ali$ make
Compiling OF library for Release
make[2]: Nothing to be done for `ReleaseABI'.
Done!

Compiling Soft for Release
../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.mk:179: The following unknown addons will be ignored:
../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.mk:180: ofxAxisGrabber
Compiling src/main.cpp
c++ -c -Os -stdlib=libstdc++ -Wall -fexceptions -march=native -mtune=native -finline-functions -arch i386 -fpascal-strings -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks -mmacosx-version-min=10.8 -fasm-blocks -funroll-loops -mssse3 -fmessage-length=0 -D__MACOSX_CORE__ -I./src -I../../../addons/ofxHttpUtils/src -I../../../addons/ofxGui/src -I../../../libs/FreeImage/include -I../../../libs/cairo/include -I../../../libs/cairo/include/cairo -I../../../libs/cairo/include/libpng15 -I../../../libs/cairo/include/pixman-1 -I../../../libs/fmodex/include -I../../../libs/freetype/include -I../../../libs/freetype/include/freetype2 -I../../../libs/freetype/include/freetype2/freetype -I../../../libs/freetype/include/freetype2/freetype/config -I../../../libs/freetype/include/freetype2/freetype/internal -I../../../libs/freetype/include/freetype2/freetype/internal/services -I../../../libs/glew/include -I../../../libs/glew/include/GL -I../../../libs/glfw/include -I../../../libs/glfw/include/GLFW -I../../../libs/glut/include -I../../../libs/openssl/include -I../../../libs/openssl/include/openssl -I../../../libs/poco/include -I../../../libs/rtAudio/include -I../../../libs/tess2/include -I../../../libs/openFrameworks -I../../../libs/openFrameworks/3d -I../../../libs/openFrameworks/app -I../../../libs/openFrameworks/communication -I../../../libs/openFrameworks/events -I../../../libs/openFrameworks/gl -I../../../libs/openFrameworks/graphics -I../../../libs/openFrameworks/math -I../../../libs/openFrameworks/sound -I../../../libs/openFrameworks/types -I../../../libs/openFrameworks/utils -I../../../libs/openFrameworks/video -x objective-c++ -MMD -MP -MF obj/osx/Release/src/main.d -MT obj/osx/Release/src/main.o -o obj/osx/Release/src/main.o -c src/main.cpp
In file included from src/main.cpp:2:
./src/ofApp.h:4:10: fatal error: 'ofxAxisGrabber.h' file not found
# include "ofxAxisGrabber.h"

```
     ^
```

1 error generated.
make[1]: **\* [obj/osx/Release/src/main.o] Error 1
make: **\* [Release] Error 2
jizbookpro:example ali$

**Comment by arturoc** [comment]
the makefile system will only find addons if the folder in which they are is named like the addon itself, you need to rename ofxAxisGrabber-master to ofxAxisGrabber you'll also need ofxHttpUtils

**Comment by batchku** [comment]
hello arturo and thanks for your answer,
i've done the necessary renaming, installed the necessary components of gstreamer from instructinos your ofGStreamer page, and also installed ofxHttpUtils.

i'm running into a problem with the make process not finding the gstreamer headers:

In file included from ./src/ofApp.h:4:
In file included from ../../../addons/ofxAxisGrabber/src/ofxAxisGrabber.h:15:
../../../libs/openFrameworks/video/ofGstUtils.h:13:10: fatal error: 'gst/gst.h' file not found
#include <gst/gst.h>

it looks like the ofGstUtils.h header wants the gst headers in its folder level?
should i copy them there?

i also tried to compile your ofGStreamer addon but i'm having trouble finding instructions for how to use the addon_config.mk configuration; i tried to run the shell script called "addon_config.mk" but got many errors; if you can point me to that i'd be grateful.

a

**Comment by arturoc** [comment]
you need to generate the project with the project generator

**Comment by batchku** [comment]
hi arturo,
i actually AM generating a new project with the project generator.
i've tried with the project generator in 0.8.2 and 0.8.3
having the same problem with both.

i posted these attempts in the ofx forum also, with the error i'm getting.

http://forum.openframeworks.cc/t/errors-compiling-ofxaxisgrabber/16333/3

**Comment by arturoc** [comment]
are you adding the ofxGStreamer addon to the project? and i guess you've installed gstreamer as explained in the readme for ofxGStreamer right?

**Comment by batchku** [comment]
Hello

On Wednesday, July 9, 2014, arturo notifications@github.com wrote:

> are you adding the ofxGStreamer addon to the project?
> 
> Yes
> 
>  and i guess you've installed gstreamer as explained in the readme for
> ofxGStreamer right?

And yes
I tried with 1.0-1.2.1 as u had and also with 1.0-1.3.9 which is the latest
if gstreamer

The compiler error reads as if it is looking for the gstreamer headers in a
local sub directory. When I manually copy this files there I see that I
finds them and moves on to the next one it can not find; all from gst

Where so u have your gst header files?

Ali

**Comment by arturoc** [comment]
you shouldn't need to copy them, you are on osx right? i've been using the ofxGStreamer addon on osx lately and didn't have any problem

**Comment by batchku** [comment]
hello,
ok, i will try again.
are you using the project generator from 0.8.3 or 0.8.2 or another ?

ali
