### ISSUE TITLE
Unable to run example in 0.9.3

### ISSUE THREAD

**Issue by rwebber** [arturoc/ofxAxisGrabber#3]
I might be doing something wrong..  a bit of a newbie, sorry.
But I get errors linking gst/ headers. (eg: "gst/gst.h")
Does some other Gstreamer stuff need to be installed?

**Comment by arturoc** [comment]
yes this addon depends on gstreamer which should work right away in linux or by using ofxGstreamer

**Comment by rwebber** [comment]
I'm setting up in Windows 10. 
Any reason this shouldn't work?
Appreciate your feedback and all the great work, I am really having fun getting rolling with OF.
